import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// cognifyiq\src\app\fonts\HelveticaNeueBlack.otf
const normal = localFont({
  src: "./fonts/HelveticaNeueBlack.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${normal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
